name: releaf_app
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  fl_chart: ^1.0.0
  sensors_plus: ^6.1.1
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.3.2
  lottie: ^3.1.2
  go_router: ^17.0.0
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.3.2
  purchases_flutter: ^9.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # ⬅️ aktualizacja
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/ui/
    - assets/games/labyrinth/level1.png
    - assets/games/labyrinth/level1_mask.png
    - assets/games/labyrinth/level2.png
    - assets/games/labyrinth/level2_mask.png
    - assets/games/labyrinth/level3.png
    - assets/games/labyrinth/level3_mask.png
    - assets/games/labyrinth/level4.png
    - assets/games/labyrinth/level4_mask.png
    - assets/animations/leaf_walk.json
    - assets/sounds/relief_01.mp3
    - assets/sounds/relief_02.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
